version: '3'

services:
  mariadb:
    image: mariadb:10.8
    container_name: mariadb
    hostname: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./db/.env
    environment:
      - TZ=Asia/Seoul
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_cache
    hostname: redis_cache
    ports:
      - 6379:6379
    restart: always
    volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./redis/cache:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server /usr/local/etc/redis/redis.conf

  fastapi01:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi01
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./app/:/app/
    environment:
      - TZ=Asia/Seoul
    command: bash -c "
      uvicorn app.main:app --host 0.0.0.0 --port 8000"